"""Lossless geometry conversion of Apple's public AR USDZ into Fourier's glTF input.
No decimation, remeshing, added geometry, or replacement materials.
"""
from pathlib import Path
import bpy,json,struct,base64,hashlib
from mathutils import Vector
root=Path(__file__).resolve().parent.parent
source=root/'assets/official/mac-mini-silver.usdz'
out=root/'assets/model'
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
bpy.ops.wm.usd_import(filepath=str(source))
meshes=[o for o in bpy.context.scene.objects if o.type=='MESH']
points=[o.matrix_world@Vector(c) for o in meshes for c in o.bound_box]
minimum=Vector(tuple(min(p[i] for p in points) for i in range(3)))
maximum=Vector(tuple(max(p[i] for p in points) for i in range(3)))
report={'source':str(source.relative_to(root)),'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'geometryOperation':'None; original mesh topology, normals and UVs retained. glTF export triangulates faces.','meshCount':len(meshes),'vertices':sum(len(o.data.vertices) for o in meshes),'polygons':sum(len(o.data.polygons) for o in meshes),'boundsMeters':{'min':list(minimum),'max':list(maximum),'size':list(maximum-minimum)},'textures':[{'name':im.name,'size':list(im.size)} for im in bpy.data.images if im.source=='FILE']}
# Pack the original imported textures so this .blend is portable.
bpy.ops.file.pack_all()
path=out/'mac-mini-official.glb'
bpy.ops.export_scene.gltf(filepath=str(path),export_format='GLB',export_apply=False,export_yup=True,export_materials='EXPORT',export_animations=False,export_cameras=False,export_lights=False)
raw=path.read_bytes();n=struct.unpack_from('<I',raw,12)[0]
gltf=json.loads(raw[20:20+n]);offset=20+n
length=struct.unpack_from('<I',raw,offset)[0];binary=raw[offset+8:offset+8+length]
encoded=base64.b64encode(binary).decode('ascii')
chunks=[encoded[i:i+1024*1024] for i in range(0,len(encoded),1024*1024)]
for i,chunk in enumerate(chunks):(out/f'official-buffer-{i}.json').write_text(json.dumps(chunk))
(out/'official-structure.json').write_text(json.dumps(gltf,separators=(',',':')))
imports="import structure from './official-structure.json';\n"+''.join(f"import buffer{i} from './official-buffer-{i}.json';\n" for i in range(len(chunks)))
(out/'official.ts').write_text('// Generated by scripts/import-official-model.py from Apple USDZ.\n'+imports+"export function officialModelJSON(): string {\n return JSON.stringify({...structure, buffers: [{...structure.buffers[0], uri: 'data:application/octet-stream;base64,' + ["+','.join(f'buffer{i}' for i in range(len(chunks)))+"].join('')}]});\n}\n")
report.update({'glbBytes':len(raw),'glbSha256':hashlib.sha256(raw).hexdigest(),'gltfMeshes':len(gltf['meshes']),'gltfMaterials':len(gltf['materials']),'gltfImages':len(gltf.get('images',[])),'embeddedBufferChunks':len(chunks),'chunkLimit':1048576,'binarySha256':hashlib.sha256(binary).hexdigest()})
(root/'review/official-model-conversion.json').write_text(json.dumps(report,indent=2))
# Set up a useful studio in the .blend; none of the studio is part of the exported GLB.
bpy.ops.mesh.primitive_plane_add(size=5,location=(0,0,-.0008))
ground=bpy.context.object;ground.name='Studio ground (not exported)'
m=bpy.data.materials.new('Studio white');m.diffuse_color=(.8,.8,.8,1);ground.data.materials.append(m)
for name,loc,power,size in [('Key',(-.12,-.15,.23),12,.22),('Rim',(.17,.12,.22),10,.2),('Fill',(.12,-.2,.08),4,.13)]:
 bpy.ops.object.light_add(type='AREA',location=loc);o=bpy.context.object;o.name=name;o.data.energy=power;o.data.size=size;o.rotation_euler=(Vector((0,0,.023))-o.location).to_track_quat('-Z','Y').to_euler()
bpy.ops.object.camera_add(location=(.22,-.3,.18));cam=bpy.context.object;cam.name='Product studio camera';cam.rotation_euler=(Vector((0,0,.023))-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.lens=55;cam.data.clip_start=.001
scene=bpy.context.scene;scene.camera=cam;scene.render.engine='CYCLES';scene.cycles.samples=32;scene.render.resolution_x=1920;scene.render.resolution_y=1080;scene.render.resolution_percentage=100;scene.world.color=(.3,.3,.3)
bpy.ops.wm.save_as_mainfile(filepath=str(out/'mac-mini-official.blend'))
print('OFFICIAL_MODEL_READY',json.dumps(report))
