// Generated by scripts/import-official-model.py from Apple USDZ.
import structure from './official-structure.json';
import buffer0 from './official-buffer-0.json';
import buffer1 from './official-buffer-1.json';
import buffer2 from './official-buffer-2.json';
import buffer3 from './official-buffer-3.json';
import buffer4 from './official-buffer-4.json';
import buffer5 from './official-buffer-5.json';
import buffer6 from './official-buffer-6.json';
export function officialModelJSON(): string {
 return JSON.stringify({...structure, buffers: [{...structure.buffers[0], uri: 'data:application/octet-stream;base64,' + [buffer0,buffer1,buffer2,buffer3,buffer4,buffer5,buffer6].join('')}]});
}
